# Generated by Django 4.1.1 on 2022-09-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.TextField(blank=True, null=True)),
                ("price", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
